{
  # Generated by nixos-generate-config for the desktop. Regenerate on the
  # machine and paste the values back here if hardware changes.
  flake.modules.nixos.redwood = {
    config,
    lib,
    modulesPath,
    ...
  }: {
    imports = [(modulesPath + "/installer/scan/not-detected.nix")];

    boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
    boot.initrd.kernelModules = [];
    boot.kernelModules = ["kvm-amd"];
    boot.extraModulePackages = [];

    fileSystems."/" = {
      device = "/dev/disk/by-uuid/220568ac-4185-4a83-b197-ffc3f6e99d7a";
      fsType = "btrfs";
      options = ["subvol=@"];
    };

    boot.initrd.luks.devices."luks-cf5815fa-8a74-4a2e-b5ab-a155893640c4".device = "/dev/disk/by-uuid/cf5815fa-8a74-4a2e-b5ab-a155893640c4";

    fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/4443-0F45";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };

    swapDevices = [
      {device = "/dev/disk/by-uuid/2f8eb71f-32eb-483c-b0c9-28a00f87ca3e";}
    ];

    networking.useDHCP = lib.mkDefault true;
    nixpkgs.hostPlatform = "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
